name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print service URL
        run: echo "https://cis410-flask-app-uonof3eja-uc.a.run.app"
